# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('InfoId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('PhoneNum', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
